### ISSUE TITLE
iOS 8.4 iPhone 5 tested ver3.0 and not working in all apps when turn on the option

### ISSUE THREAD

**Issue by KennethWKZ** [Naville/ManualVPN#1]
As title, I tried to turn on ManuallyVPN option for many system and common apps. But seems like when I open the apps, it did not automatically open the vpn.

**Comment by Naville** [comment]
-(id)startPersonalConnection:(id)arg1 ;
-(id)startEnterpriseConnection:(id)arg1 ;

The system divides VPNs into two types and the tweak must call corresponding method to start the connection.
By default this tweak calls startPersonalConnection.

Will fix this issue when I got my jailbreak device back

**Comment by Naville** [comment]
fixed. thanks to someone for testing.
Should appear in bigboss in a few days

**Comment by KennethWKZ** [comment]
Good to hear this news! Thanks!

Thank You.
Regards,
Kenneth Wong

**Comment by Naville** [comment]
Uploaded to BB but seems like my Mac messed up permissions.
You need to manually set the permissions of /Library/PreferenceLoader/Preferences/ManualVPN.plist

**Comment by Naville** [comment]
Should be mobile:mobile.
read write for all

**Comment by z7x** [comment]
Hey,

It doesn't seem to work at all on my iPhone 6s+ 9.0.2. I can't see any ManualVPN settings. 

Please could you help?

Maciek

**Comment by KennethWKZ** [comment]
Just update to 5.0.0 version but I check the preference plist with text editor. Inside not the standard plist format. Please fix it.

Thanks & Regards,
Kenneth
